/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "sdccc_parent"
include(":biceps-model")
include(":dpws-model")
include(":sdccc")

val defaultVersion = "9.1.0-SNAPSHOT"

val actualRevision = providers.gradleProperty("revision").orElse(defaultVersion).get()
val actualChangelist = providers.gradleProperty("changelist").orElse("").get()

gradle.rootProject {
    extra["projectVersion"] = "$actualRevision$actualChangelist"
}