/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

gradlePlugin {
    plugins {
        create("XjcPlugin") {
            id = "org.somda.sdc.xjc"
            implementationClass = "org.somda.sdc.XjcPlugin"
        }
        create("licenseReport") {
            id = "com.example.license-report"
            implementationClass = "LicenseReportPlugin"
        }
    }
}

dependencies {
    implementation("com.github.jk1:gradle-license-report:2.0")
}
