/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

val actualRevision = checkNotNull(project.findProperty("revision")) { "No revision property configured" }
val actualChangeList = checkNotNull(project.findProperty("changelist")) { "No changelist property configured" }

group = "com.draeger.medical"
version = "$actualRevision$actualChangeList"

tasks.withType<Jar> {
    manifest {
        attributes["Implementation-Title"] = project.name
        attributes["Implementation-Version"] = project.version
    }
}