/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

val actualRevision = checkNotNull(project.findProperty("revision")) { "No internalRevision property configured" }
val actualChangeList = checkNotNull(project.findProperty("changelist")) { "No internalChangelist property configured" }

group = "com.draeger.medical"
version = "$actualRevision$actualChangeList"
