/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

val actualRevision = project.findProperty("revision") ?: ""
val actualChangeList = project.findProperty("changelist") ?: ""

group = "com.draeger.medical"
version = "$actualRevision$actualChangeList"
