name: Check license headers

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push: # Apply to all branches

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      - uses: maximilianpilz/file-header-check@v1
        with:
          config: '.github/license-check/license-config'
          config-encoding: 'utf-8'
          log-level: 'DEBUG'
