name: Check license headers

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push: # Apply to all branches

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      - uses: viperproject/check-license-header@v1
        with:
          path: .
          config: .github/license-check/license-config.json
          strict: false # <boolean indicating whether files not covered by the configuration should be reported as errors>